### PR TITLE
Big data options

### PR DESCRIPTION
**Pull request by bcohen07**
Hey guys - what do you think of my "big data" summary? Would love some feedback. Or even better, just a +1. Let's ship this code!

@koo512 @etekis @ldk616

### CODE REVIEW

**Comment by ldk616** [comment]
@bcohen07 – this looks great! One thing you could add is a link to current trends in the Big Data space
-   Check on the [Top 8 Trends in Big Data](http://tinyurl.com/jlsmxut)

Great work! Thumbs up :+1: and ready to ship!

**Comment by etekis** [comment]
@bcohen07 for some reason it says there's a conflict with your branch. Can you check?

Otherwise it's a massive :+1:

**Comment by koo512** [comment]
@bcohen07 thumbs up from me! :+1:

**Comment by etekis** [comment]
We merged the new updated one instead

**Pull request closed without merging**
